//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagner.NamingStyles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wagner.NamingStyles.CodeFixesResources", typeof(CodeFixesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add blank line after block.
        /// </summary>
        internal static string Add_blank_line_after_block {
            get {
                return ResourceManager.GetString("Add_blank_line_after_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add both.
        /// </summary>
        internal static string Add_both {
            get {
                return ResourceManager.GetString("Add_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add default case.
        /// </summary>
        internal static string Add_default_case {
            get {
                return ResourceManager.GetString("Add_default_case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file header.
        /// </summary>
        internal static string Add_file_header {
            get {
                return ResourceManager.GetString("Add_file_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix all occurrences in.
        /// </summary>
        internal static string Fix_all_occurrences_in {
            get {
                return ResourceManager.GetString("Fix_all_occurrences_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Name Violation: {0}.
        /// </summary>
        internal static string Fix_Name_Violation_colon_0 {
            get {
                return ResourceManager.GetString("Fix_Name_Violation_colon_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove extra blank lines.
        /// </summary>
        internal static string Remove_extra_blank_lines {
            get {
                return ResourceManager.GetString("Remove_extra_blank_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove redundant assignment.
        /// </summary>
        internal static string Remove_redundant_assignment {
            get {
                return ResourceManager.GetString("Remove_redundant_assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress or Configure issues.
        /// </summary>
        internal static string Suppress_or_Configure_issues {
            get {
                return ResourceManager.GetString("Suppress_or_Configure_issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update suppression format.
        /// </summary>
        internal static string Update_suppression_format {
            get {
                return ResourceManager.GetString("Update_suppression_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use discard &apos;_&apos;.
        /// </summary>
        internal static string Use_discard_underscore {
            get {
                return ResourceManager.GetString("Use_discard_underscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use discarded local.
        /// </summary>
        internal static string Use_discarded_local {
            get {
                return ResourceManager.GetString("Use_discarded_local", resourceCulture);
            }
        }
    }
}
