//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagner.NamingStyles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wagner.NamingStyles.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing prefix: &apos;{0}&apos;.
        /// </summary>
        internal static string Missing_prefix_colon_0 {
            get {
                return ResourceManager.GetString("Missing_prefix_colon_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing suffix: &apos;{0}&apos;.
        /// </summary>
        internal static string Missing_suffix_colon_0 {
            get {
                return ResourceManager.GetString("Missing_suffix_colon_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix &apos;{0}&apos; does not match expected prefix &apos;{1}&apos;.
        /// </summary>
        internal static string Prefix_0_does_not_match_expected_prefix_1 {
            get {
                return ResourceManager.GetString("Prefix_0_does_not_match_expected_prefix_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix &apos;{0}&apos; is not expected.
        /// </summary>
        internal static string Prefix_0_is_not_expected {
            get {
                return ResourceManager.GetString("Prefix_0_is_not_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first word, &apos;{0}&apos;, must begin with a lower case character.
        /// </summary>
        internal static string The_first_word_0_must_begin_with_a_lower_case_character {
            get {
                return ResourceManager.GetString("The_first_word_0_must_begin_with_a_lower_case_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first word, &apos;{0}&apos;, must begin with an upper case character.
        /// </summary>
        internal static string The_first_word_0_must_begin_with_an_upper_case_character {
            get {
                return ResourceManager.GetString("The_first_word_0_must_begin_with_an_upper_case_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These non-leading words must begin with a lowercase letter: {0}.
        /// </summary>
        internal static string These_non_leading_words_must_begin_with_a_lowercase_letter_colon_0 {
            get {
                return ResourceManager.GetString("These_non_leading_words_must_begin_with_a_lowercase_letter_colon_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These non-leading words must begin with an upper case letter: {0}.
        /// </summary>
        internal static string These_non_leading_words_must_begin_with_an_upper_case_letter_colon_0 {
            get {
                return ResourceManager.GetString("These_non_leading_words_must_begin_with_an_upper_case_letter_colon_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These words cannot contain lower case characters: {0}.
        /// </summary>
        internal static string These_words_cannot_contain_lower_case_characters_colon_0 {
            get {
                return ResourceManager.GetString("These_words_cannot_contain_lower_case_characters_colon_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These words cannot contain upper case characters: {0}.
        /// </summary>
        internal static string These_words_cannot_contain_upper_case_characters_colon_0 {
            get {
                return ResourceManager.GetString("These_words_cannot_contain_upper_case_characters_colon_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These words must begin with upper case characters: {0}.
        /// </summary>
        internal static string These_words_must_begin_with_upper_case_characters_colon_0 {
            get {
                return ResourceManager.GetString("These_words_must_begin_with_upper_case_characters_colon_0", resourceCulture);
            }
        }
    }
}
